spring:
  redis:
    host: 101.43.18.103
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
    password: '000415'

  # 支持 swagger3
  swagger:
    enabled: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      # 大小限制
      max-file-size: 20MB
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.18.103:3306/seven-ems?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: seven-ems
    password: seven-ems
  # 将 Quartz 持久化方式修改为 jdbc
  profiles:
    default:
#  quartz:
#    jobStoreType: jdbc
#    jdbc:
#      initialize-schema: always
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: SC_Scheduler
#            instanceId: AUTO
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            dataSource: quartz_jobs
#            quartz_jobs:
#              driver: com.mysql.cj.jdbc.Driver
#              URL: dbc:mysql://127.0.0.1:3306/quartz_jobs?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
#              user: root
#              password: 123456


#  profiles:
#    active: application-cos.yaml
# minio 配置
minio:
  endpoint: http://101.43.18.103:9001
  bucket-name: mes-bucket
  access-key: 5vAkUNis1yRivhy7
  secret-key: trwes1lppuOm9IIQxW5gwvArsmgbtJLq
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: IsDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
  mapper-locations: classpath*:/mapper/*Mapper.xml
#  mapper-locations: classpath*:mapper/*.xml
jwt:
  # 加密密钥
  secret: abcdefg1234567
  # token有效时长
  expire: 1800000
  # header 名称
  header: token
email:
  host: smtp.qq.com
  port:
  username:
  password:
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
crypto:
  md5:
    salt: 123456

default:
  avatar: http://101.43.18.103:9001/mes-bucket/Avatar/defaultAvatar.png