name: Deploy springboot with docker

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
        # maven缓存，不加的话每次都会去重新拉取，会影响速度
      - name: Dependency Cache
        uses: actions/cache@v2
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        # 编译打包
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
      # 登录Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      # build 镜像并push到中央仓库中
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/ems-backend:latest
      # push后，用ssh连接服务器执行脚本
      - name: SSH
        uses: appleboy/ssh-action@master
        with:          
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PWD }}
          key: ${{ secrets.HOST_TOKEN}}
          script: |
            docker pull lbaixiaofei/ems-backend:latest
            docker rm -f homework-back
            docker run --name=ems-back -d -p 8101:8101 lbaixiaofei/ems-backend:latest
            docker image prune -af
